site_name: Лабораторные работы по Веб-разработке - Бородин Максим K3341
site_description: Отчеты по лабораторным работам курса "Веб-программирование"
site_author: Бородин Максим

# Репозиторий
repo_name: 'GitHub'
repo_url: 'https://github.com/your-username/your-repo-name'

# Настройки темы
theme:
  name: material
  language: ru
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Переключить на тёмную тему
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Переключить на светлую тему
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.annotate
    - content.code.copy

# Навигация
nav:
  - Главная: index.md
  - Лабораторная работа №1:
    - Отчет: index.md

# Расширения Markdown
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
  - attr_list
  - md_in_html

# Плагины
plugins:
  - search:
      lang: ru

# Дополнительные CSS
extra_css:
  - stylesheets/extra.css

# Дополнительные настройки
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-username
